export const data = [
  [
    [
      "Who is the director of the dark knight trilogy ?",
      { answer: "Christopher Nolan", isTrue: true },
      { answer: "Zack Snyder", isTrue: false },
      { answer: "Quentin Tarantino", isTrue: false },
      { answer: "James Cameron", isTrue: false },
    ],
    [
      "Who played the protagonist in the dark knight trilogy ?",
      { answer: "Ben Affleck", isTrue: false },
      { answer: "Cillian Murphy", isTrue: false },
      { answer: "Christian Bale", isTrue: true },
      { answer: "Robert Pattinson", isTrue: false },
    ],
    [
      "What character did Liam Neeson played in batman begins ?",
      { answer: "The Joker", isTrue: false },
      { answer: "Bane", isTrue: false },
      { answer: "Commissioner Gordon", isTrue: false },
      { answer: "Ras Al Ghul", isTrue: true },
    ],
    [
      "Who played Alfred's Character in the dark knight trilogy ?",
      { answer: "Sean Pertwee", isTrue: false },
      { answer: "Andy Serkis", isTrue: false },
      { answer: "Jeremy Irons", isTrue: false },
      { answer: "Michael Caine", isTrue: true },
    ],
    [
      "What Character did Aaron Eckhart play in the dark knight ?",
      { answer: "Bruce Wayne", isTrue: false },
      { answer: "Harvey Dent ", isTrue: true },
      { answer: "Scarecrow", isTrue: false },
      { answer: "Mayor Anthony Garcia", isTrue: false },
    ],
    [
      "What was the name of Bruce Wayne's Father ?",
      { answer: "Michael Wayne", isTrue: false },
      { answer: "Thomas Wayne", isTrue: true },
      { answer: "Chris Wayne", isTrue: false },
      { answer: "Tom Wayne", isTrue: false },
    ],
    [
      "What is the name of Bruce Wayne's childhood friend ?",
      { answer: "Rachel", isTrue: true },
      { answer: "Sophia", isTrue: false },
      { answer: "Celina", isTrue: false },
      { answer: "Sara", isTrue: false },
    ],
    [
      "What Character did Morgan Freeman Played in the trilogy ?",
      { answer: "Alfred", isTrue: false },
      { answer: "Robin", isTrue: false },
      { answer: "Lucius Fox", isTrue: true },
      { answer: "Harvey Dent", isTrue: false },
    ],
    [
      "Who played the joker in the dark knight ?",
      { answer: "Heath Ledger", isTrue: true },
      { answer: "Jared Leto", isTrue: false },
      { answer: "Joaquin Phoenix", isTrue: false },
      { answer: "Matthew McConaughey", isTrue: false },
    ],
    [
      "Who played Bane Character in the dark knight rises ?",
      { answer: "Matt Damon", isTrue: false },
      { answer: "Tom Hardy", isTrue: true },
      { answer: "Vin Diesel", isTrue: false },
      { answer: "Daniel Craig", isTrue: false },
    ],
  ],
  [
    [
      "What frighten Bruce Wayne ?",
      { answer: "Cats", isTrue: false },
      { answer: "Bats", isTrue: true },
      { answer: "Dogs", isTrue: false },
      { answer: "Wolves", isTrue: false },
    ],
    [
      "What tragedy happened to Bruce Wayne when he was a child ?",
      { answer: "His mother was kidnapped", isTrue: false },
      { answer: "They killed his girlfriend", isTrue: false },
      { answer: "The murder of his parent", isTrue: true },
      { answer: "His father went bankrupt", isTrue: false },
    ],
    [
      "In order to understand the crime world, what did Bruce Wayne do ?",
      { answer: "He became a cop", isTrue: false },
      { answer: "He studied Criminology", isTrue: false },
      { answer: "he became Batman", isTrue: false },
      { answer: "He lived among criminals for years", isTrue: true },
    ],
    [
      "Who was Bruce Wayne trained by ?",
      { answer: "Alfred", isTrue: false },
      { answer: "His Father", isTrue: false },
      { answer: "By himself", isTrue: false },
      { answer: "Henri Ducard", isTrue: true },
    ],
    [
      "Why did Bruce Wayne leave the league of shadows ?",
      { answer: "They killed his parents", isTrue: false },
      { answer: "he doesn't want to be an executioner", isTrue: true },
      { answer: "They were criminals", isTrue: false },
      { answer: "He was never a member ", isTrue: false },
    ],
    [
      "Why did Bruce Wayne come back to Gotham ?",
      {
        answer: "He wanted revenge",
        isTrue: false,
      },
      {
        answer: "He wanted to fight Gotham's criminals",
        isTrue: true,
      },
      { answer: "He missed his old friends", isTrue: false },
      { answer: "He wanted to fulfill his father's dream", isTrue: false },
    ],
    [
      "Who supplies Batman with equipments ?",
      { answer: "Lucius Fox", isTrue: true },
      { answer: "Alfred", isTrue: false },
      { answer: "He builds them himself", isTrue: false },
      { answer: "He buys them", isTrue: false },
    ],
    [
      "Who is the ally of Batman ?",
      { answer: "Falcony", isTrue: false },
      { answer: "Ras Al Ghul", isTrue: false },
      { answer: "Commissioner Gordon", isTrue: true },
      { answer: "The cops", isTrue: false },
    ],
    [
      "How many times did Bruce Wayne rescue Ducard from Death ?",
      { answer: "Once", isTrue: true },
      { answer: "Twice", isTrue: false },
      { answer: "3 times", isTrue: false },
      { answer: "4 times", isTrue: false },
    ],
    [
      "What's the main theme of Batman begins ?",
      { answer: "Hope", isTrue: false },
      { answer: "Fear", isTrue: true },
      { answer: "Triumph", isTrue: false },
      { answer: "Dispair", isTrue: false },
    ],
  ],
  [
    [
      "What was the opening scene of The dark knight ?",
      { answer: "Batman entry ", isTrue: false },
      { answer: "Bank robbery ", isTrue: true },
      { answer: "Fake Batman ", isTrue: false },
      { answer: "Joker story ", isTrue: false },
    ],
    [
      "Who says 'I make my own luck' ?",
      { answer: "Bruce Wayne", isTrue: false },
      { answer: "Alfred", isTrue: false },
      { answer: "The Joker", isTrue: false },
      { answer: "Harvey Dent", isTrue: true },
    ],
    [
      "What was the joker's offer to the criminals ?",
      { answer: " Killing the Batman", isTrue: true },
      { answer: " Buying the cops", isTrue: false },
      { answer: " Doing their businesses at daytime", isTrue: false },
      { answer: " Send heir money abroad", isTrue: false },
    ],
    [
      "Who kidnapped Lau from Hong kong ?",
      { answer: "The SWAT team", isTrue: false },
      { answer: "Maroni", isTrue: false },
      { answer: "The Joker", isTrue: false },
      { answer: "Batman", isTrue: true },
    ],
    [
      "What was the Joker's condition to stop killing people ?",
      { answer: "He asked for 2 million dollars", isTrue: false },
      { answer: "The Batman should turn himself in", isTrue: true },
      { answer: "He wanted Batman to be sentenced to death", isTrue: false },
      { answer: "There was no condition ", isTrue: false },
    ],
    [
      "Who faked his death ?",
      {
        answer: "The Batman",
        isTrue: false,
      },
      {
        answer: "Harvey Dent",
        isTrue: false,
      },
      { answer: "Commissioner Gordon", isTrue: true },
      { answer: "The Joker", isTrue: false },
    ],
    [
      "How did the joker escape from the MCU ?",
      { answer: "He injected a bomb in one of the prisoners", isTrue: true },
      { answer: "There were traitors in the MCU", isTrue: false },
      { answer: "His friends got him out", isTrue: false },
      { answer: "He's never been caught in the MCU", isTrue: false },
    ],
    [
      "Who died at 250 52's street ?",
      { answer: "Harvey Dent", isTrue: false },
      { answer: "The Joker", isTrue: false },
      { answer: " Rachel", isTrue: true },
      { answer: "Gambol", isTrue: false },
    ],
    [
      "what was The Joker's condition to not blow up the Hospital ?",
      { answer: "There was no condition", isTrue: false },
      { answer: "Reese should be dead", isTrue: false },
      { answer: "Batman should reveal his identity", isTrue: false },
      { answer: "Harvey Dent should resign", isTrue: true },
    ],
    [
      " He's a silent guardian, a watchful protector, ...",
      { answer: "The Batman", isTrue: false },
      { answer: "The dark knight", isTrue: true },
      { answer: "He is our hero", isTrue: false },
      { answer: "But not the one we need", isTrue: false },
    ],
  ],
];
