export const data = [
  [
    [
      "Who is the director of the dark knight trilogy ?",
      { answer: "Christopher Nolan", isTrue: true },
      { answer: "Zack Snyder", isTrue: false },
      { answer: "Quentin Tarantino", isTrue: false },
      { answer: "James Cameron", isTrue: false },
    ],
    [
      "Who played the protagonist in the dark knight trilogy ?",
      { answer: "Ben Affleck", isTrue: false },
      { answer: "Cillian Murphy", isTrue: false },
      { answer: "Christian Bale", isTrue: true },
      { answer: "Robert Pattinson", isTrue: false },
    ],
    [
      "What character did Liam Neeson played in batman begins ?",
      { answer: "The Joker", isTrue: false },
      { answer: "Bane", isTrue: false },
      { answer: "Commissioner Gordon", isTrue: false },
      { answer: "Ras Al Ghul", isTrue: true },
    ],
    [
      "Who played Alfred's Character in the dark knight trilogy ?",
      { answer: "Sean Pertwee", isTrue: false },
      { answer: "Andy Serkis", isTrue: false },
      { answer: "Jeremy Irons", isTrue: false },
      { answer: "Michael Caine", isTrue: true },
    ],
    [
      "What Character did Aaron Eckhart play in the dark knight ?",
      { answer: "Bruce Wayne", isTrue: false },
      { answer: "Harvey Dent ", isTrue: true },
      { answer: "Scarecrow", isTrue: false },
      { answer: "Mayor Anthony Garcia", isTrue: false },
    ],
    [
      "What was the name of Bruce Wayne's Father ?",
      { answer: "Michael Wayne", isTrue: false },
      { answer: "Thomas Wayne", isTrue: true },
      { answer: "Chris Wayne", isTrue: false },
      { answer: "Tom Wayne", isTrue: false },
    ],
    [
      "What is the name of Bruce Wayne's childhood friend ?",
      { answer: "Rachel", isTrue: true },
      { answer: "Sophia", isTrue: false },
      { answer: "Celina", isTrue: false },
      { answer: "Sara", isTrue: false },
    ],
    [
      "What Character did Morgan Freeman Played in the trilogy ?",
      { answer: "Alfred", isTrue: false },
      { answer: "Robin", isTrue: false },
      { answer: "Lucius Fox", isTrue: true },
      { answer: "Harvey Dent", isTrue: false },
    ],
    [
      "Who played the joker in the dark knight ?",
      { answer: "Heath Ledger", isTrue: true },
      { answer: "Jared Leto", isTrue: false },
      { answer: "Joaquin Phoenix", isTrue: false },
      { answer: "Matthew McConaughey", isTrue: false },
    ],
    [
      "Who played Bane Character in the dark knight rises ?",
      { answer: "Matt Damon", isTrue: false },
      { answer: "Tom Hardy", isTrue: true },
      { answer: "Vin Diesel", isTrue: false },
      { answer: "Daniel Craig", isTrue: false },
    ],
  ],
  [
    [
      "What frighten Bruce Wayne ?",
      { answer: "Cats", isTrue: false },
      { answer: "Bats", isTrue: true },
      { answer: "Dogs", isTrue: false },
      { answer: "Wolves", isTrue: false },
    ],
    [
      "What tragedy happened to Bruce Wayne when he was a child ?",
      { answer: "he watched his mother engulfed in ilames", isTrue: false },
      { answer: "The death of his dearest friend", isTrue: false },
      { answer: "The murder of his parent", isTrue: true },
      { answer: "His father went bankrupt", isTrue: false },
    ],
    [
      "In order to understand the crime world, what did Bruce Wayne do ?",
      { answer: "He became a cop", isTrue: false },
      { answer: "He studied Criminology", isTrue: false },
      { answer: "he became Batman", isTrue: false },
      { answer: "He lived among criminals for years", isTrue: true },
    ],
    [
      "Who was Bruce Wayne trained by ?",
      { answer: "Alfred", isTrue: false },
      { answer: "His Father", isTrue: false },
      { answer: "By himself", isTrue: false },
      { answer: "Henri Ducard", isTrue: true },
    ],
    [
      "Why did Bruce Wayne leave the league of shadows ?",
      { answer: "He found out they killed his parents", isTrue: false },
      { answer: "he doesn't want to be an executioner", isTrue: true },
      { answer: "They were criminals", isTrue: false },
      { answer: "He was never a member ", isTrue: false },
    ],
    [
      "Why did Bruce Wayne come back to Gotham after quiting the league of shadows ?",
      {
        answer: "He wanted to build a team to fight criminals ",
        isTrue: false,
      },
      {
        answer: "He wanted to prove that Gotham is not for criminals",
        isTrue: true,
      },
      { answer: "He was looking for his childhood friend ", isTrue: false },
      { answer: "He wanted to work on his father's entreprise", isTrue: false },
    ],
    [
      "Who supplies Batman with equipments ?",
      { answer: "Lucius Fox", isTrue: true },
      { answer: "Alfred", isTrue: false },
      { answer: "He builds them himself", isTrue: false },
      { answer: "He buys them", isTrue: false },
    ],
    [
      "Who is the ally of Batman ?",
      { answer: "Falcony", isTrue: false },
      { answer: "Ras Al Ghul", isTrue: false },
      { answer: "Commissioner Gorden", isTrue: true },
      { answer: "The cops", isTrue: false },
    ],
    [
      "How many times did Bruce Wayne rescue Ducard from Death ?",
      { answer: "Once", isTrue: true },
      { answer: "Twice", isTrue: false },
      { answer: "3 times", isTrue: false },
      { answer: "4 times", isTrue: false },
    ],
    [
      "What's the main theme of Batman begins ?",
      { answer: "Hope", isTrue: false },
      { answer: "Fear", isTrue: true },
      { answer: "Triumph", isTrue: false },
      { answer: "Dispair", isTrue: false },
    ],
  ],
];
