export const data = [
  [
    "Who is the director of the dark knight trilogy ?",
    { answer: "Christopher Nolan", isTrue: true },
    { answer: "Zack Snyder", isTrue: false },
    { answer: "Quentin Tarantino", isTrue: false },
    { answer: "James Cameron", isTrue: false },
  ],
  [
    "Who played the protagonist in the dark knight trilogy ?",
    { answer: "Ben Affleck", isTrue: false },
    { answer: "Cillian Murphy", isTrue: false },
    { answer: "Christian Bale", isTrue: true },
    { answer: "Robert Pattinson", isTrue: false },
  ],
  [
    "What character did Liam Neeson played in batman begins ?",
    { answer: "The Joker", isTrue: false },
    { answer: "Bane", isTrue: false },
    { answer: "Commissioner Gordon", isTrue: false },
    { answer: "Ras Al Ghul", isTrue: true },
  ],
  [
    "When was Batman begins released ?",
    { answer: "2003", isTrue: false },
    { answer: "2008", isTrue: false },
    { answer: "2012", isTrue: false },
    { answer: "2005", isTrue: true },
  ],
  [
    "What Frighten Bruce Wayne the most ?",
    { answer: "Dogs", isTrue: false },
    { answer: "Bats", isTrue: true },
    { answer: "Cats", isTrue: false },
    { answer: "Wolves", isTrue: false },
  ],
  [
    "What was the name of Bruce Wayne's Father ?",
    { answer: "Michael Wayne", isTrue: false },
    { answer: "Thomas Wayne", isTrue: true },
    { answer: "Chris Wayne", isTrue: false },
    { answer: "Tom Wayne", isTrue: false },
  ],
  [
    "What is the name of Bruce Wayne's childhood friend ?",
    { answer: "Rachel", isTrue: true },
    { answer: "Sophia", isTrue: false },
    { answer: "Celina", isTrue: false },
    { answer: "Sara", isTrue: false },
  ],
  [
    "What Character did Morgan Freeman Played in the trilogy ?",
    { answer: "Alfred", isTrue: false },
    { answer: "Robin", isTrue: false },
    { answer: "Lucius Fox", isTrue: true },
    { answer: "Harvey Dent", isTrue: false },
  ],
  [
    "Who played the joker in the dark knight ?",
    { answer: "Heath Ledger", isTrue: true },
    { answer: "Jared Leto", isTrue: false },
    { answer: "Joaquin Phoenix", isTrue: false },
    { answer: "Matthew McConaughey", isTrue: false },
  ],
  [
    "Who played Bane Character in the dark knight rises ?",
    { answer: "Matt Damon", isTrue: false },
    { answer: "Tom Hardy", isTrue: true },
    { answer: "Vin Diesel", isTrue: false },
    { answer: "Daniel Craig", isTrue: false },
  ],
];
